### ISSUE TITLE
Usage sample

### ISSUE THREAD

**Issue by buble** [rainyt/openfl-3d#1]
Hi @rainyt 

I need to render basic 3d model(OBJ) in openfl display list(on top of some Sprites, Bitmaps)

your library looks exactly like this

Is there some samples?
trying to render 3d cube at least, but I see nothing

```haxe
package;

import zygame.lights.Light;
import openfl.display.Sprite;
import zygame.display3d.CubeDisplayObject;

class Main extends Sprite
{
	public function new()
	{
		super();

		var sprite:Sprite = new Sprite();
		sprite.graphics.clear();
		sprite.graphics.beginFill( 0x0000ff, 1.0 );
		sprite.graphics.drawRect( 0, 0, stage.stageWidth, stage.stageHeight );
		sprite.graphics.endFill();
		addChild(sprite);


		var d3d = new CubeDisplayObject();
		d3d.x = stage.stageWidth / 2;
		d3d.y = stage.stageHeight / 2;
		this.addChild(d3d);
		//d3d.width = 20;
		//d3d.height = 20;
		//d3d.light = new Light(-100, -100, -100);

		
	}
}
```

**Comment by rainyt** [comment]
OH! Don't support new OpenFL version.

**Comment by buble** [comment]
hmm,

I tried 
haxe 4.2.5
openfl 9.1.0
lime 7.9.0

still no luck
any ideas how to fix this?

**Comment by rainyt** [comment]
Can you try use OpenFl version 8.9.0+ ?

**Comment by rainyt** [comment]
I find `RenderEvent` not send to my Class.

**Comment by rainyt** [comment]
I investigated and found that the new version of Openfl seems to have affected some things, and I am no longer able to run it properly.

**Comment by buble** [comment]
I tried different opnenfl and lime versions, but no luck

maybe there is some other solution

**Comment by rainyt** [comment]
Can you try update github's openfl-3d last version? 
Can render 3d Object now.

**Comment by rainyt** [comment]
I add a Samples to the github.

**Comment by buble** [comment]
Thanks for help

still trying to make it working
I'm using it on static platform

```bash
haxelib git openfl-glsl https://github.com/rainyt/openfl-glsl.git
haxelib git openfl-3d https://github.com/rainyt/openfl-3d.git
openfl test windows
```

```
C:/HaxeToolkit/haxe/lib/openfl-3d/git/src/zygame/data/anim/Skeleton.hx:57: characters 11-15 : On static platforms, null can't be used as basic type Int
C:/HaxeToolkit/haxe/lib/openfl-3d/git/src/zygame/data/anim/Skeleton.hx:88: characters 11-15 : On static platforms, null can't be used as basic type Int
C:/HaxeToolkit/haxe/lib/openfl-3d/git/src/zygame/data/anim/SkeletonPose.hx:86: characters 11-15 : On static platforms, null can't be used as basic type Int
C:/HaxeToolkit/haxe/lib/openfl-3d/git/src/zygame/data/anim/SkeletonPose.hx:117: characters 11-15 : On static platforms, null can't be used as basic type Int
C:/HaxeToolkit/haxe/lib/openfl-3d/git/src/zygame/data/anim/Skeleton.hx:57: characters 11-15 : On static platforms, null can't be used as basic type Int
C:/HaxeToolkit/haxe/lib/openfl-3d/git/src/zygame/data/anim/Skeleton.hx:88: characters 11-15 : On static platforms, null can't be used as basic type Int
C:/HaxeToolkit/haxe/lib/openfl-3d/git/src/zygame/data/anim/SkeletonPose.hx:86: characters 11-15 : On static platforms, null can't be used as basic type Int
C:/HaxeToolkit/haxe/lib/openfl-3d/git/src/zygame/data/anim/SkeletonPose.hx:117: characters 11-15 : On static platforms, null can't be used as basic type Int
PS C:\HaXe\open3d> 
```

I tried to change **return null;** to **return -1;**

but then it shows shader compilation error
```
Error : Error compiling vertex shader
ERROR: 0:1: 'precision' : syntax error: syntax error

precision mediump float;
attribute vec3 zy_pos;
attribute vec3 zy_normal;
attribute vec2 zy_coord;
attribute vec4 zy_color;
attribute vec4 boneWeight;
```

**Comment by buble** [comment]
please share your haxe lime openfl versions
did you use  openfl test html5 ?

**Comment by rainyt** [comment]
Yes, I test html5 platform. 
My libs:
OpenFl: https://github.com/rainyt/openfl
Lime: https://github.com/rainyt/lime

**Comment by rainyt** [comment]
And I fix C++ error, but there are some issues with rendering.

**Comment by rainyt** [comment]
Maybe there's no problem with the windows. I test in Mac os.

**Comment by buble** [comment]
hmm, 
I don't see 3d object on windows at all

on M1 Mac I see "somehow cropped cube"
<img width="400" alt="Screenshot 2023-08-25 at 14 21 48" src="https://github.com/rainyt/openfl-3d/assets/6225437/f8e71e91-e710-418d-ab6e-06c7aa28fb80">

**Comment by rainyt** [comment]
Yes, but I don't yet know where the problem occurred.

**Comment by rainyt** [comment]
It seems to be related to depth detection.

**Comment by rainyt** [comment]
Changed `DisplayObject3D.hx`
```haxe
gl.enable(gl.DEPTH_TEST);
gl.depthFunc(gl.LESS);
gl.depthMask(false);
```
Turn off depth detection and you should be able to see something. 
but of course, this is not what we want.

**Comment by buble** [comment]
hmm still doesn't work

anyway thanks for help
your library code is usefull example

I think I'll choose other approach for my project
